title: Utah Valley Mutual Aid
email: utahvalleymutualaid@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Organizing resources & support for our communities.
show_excerpts: false # set to true to show excerpts on the homepage
baseurl: 
url: https://utahmutualaid.org

# Minima date format
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Utah Valley Mutual Aid
  tagline: Organizing resources & support for our communities.
  date_format: "%b %-d, %Y"
  style: blue
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    facebook: https://www.facebook.com/groups/utahmutualaid/
    github: utahmutualaid
    instagram: https://www.instagram.com/utahmutualaid/
    twitter: utahmutualaid
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - /about.md

# Build settings
remote_theme: thelehhman/texture
theme: texture

plugins:
  - jekyll-seo-tag